import:
  - ~/.alacritty-colorscheme/themes/gruvbox_dark.yaml

selection:
  save_to_clipboard: true

startup_mode: Maximized

font:
  normal:
    family: Hack
  bold:
    family: Hack
  italic:
    family: Hack
  bold_italic:
    family: Hack
