import = ["/home/tama/.config/alacritty/themes/themes/dracula.toml"]
#startup_mode = "Maximized"

[font.bold]
family = "Hack Nerd Font Mono"

[font.bold_italic]
family = "Hack Nerd Font Mono"

[font.italic]
family = "Hack Nerd Font Mono"

[font.normal]
family = "Hack Nerd Font Mono"

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/zsh"
